server.port=${PORT:8080}

# MYSQL CONFIGURATION FOR PRODUCTION (RAILWAY)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

# DRIVER MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# DIALECTO MYSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# SUBIDA DE ARCHIVOS
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB
server.tomcat.max-swallow-size=500MB

# SENDGRID
sendgrid.api.key=${SENDGRID_API_KEY:test}
sendgrid.from-email=diosdadogonzalesnoa@gmail.com
sendgrid.from-name=Agenda Estudiantil